name: pohps_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  go_router: ^12.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  google_fonts: ^6.1.0
  flutter_local_notifications: ^19.5.0
  video_player: ^2.8.1
  chewie: ^1.7.1
  dio: ^5.3.3
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  sqflite: ^2.4.2
  table_calendar: ^3.1.3
  flutter_markdown: ^0.7.7+1
  video_thumbnail: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/logo/
    - assets/images/
